import 'server-only';
import { createAdminClient } from '@/lib/supabase/admin';

/**
 * Putting the assistant on the site without anyone touching HTML.
 *
 * The widget was only ever available as a <script> tag to paste, which is a
 * reasonable thing to offer someone who already has a site somewhere else and a
 * useless thing to ask of the person this product is for. On a site Lumen
 * serves — the preview and the published address — Lumen can simply put it
 * there, and "live on the site" means live on the site.
 *
 * The tag stays available for pasting elsewhere; it is no longer the only way.
 */

/** The embed key of this project's assistant, when it is switched on. */
export async function liveChatbotKey(projectId: string): Promise<string | null> {
  const { data } = await createAdminClient()
    .from('chatbots')
    .select('embed_key, is_active')
    .eq('project_id', projectId)
    .maybeSingle();

  if (!data || data.is_active !== true) return null;
  const key = data.embed_key;
  // Keys are generated by us and are url-safe; anything else is not written in.
  return typeof key === 'string' && /^[\w-]{8,128}$/.test(key) ? key : null;
}

/**
 * Adds the widget to a page, root-relative so it is same-origin wherever the
 * page is being served from.
 */
export function withChatbot(html: string, embedKey: string | null): string {
  if (!embedKey || html.includes('/api/chatbot/')) return html;

  const tag = `<script src="/api/chatbot/${embedKey}/widget" defer></script>`;
  return html.includes('</body>') ? html.replace(/<\/body>/i, `${tag}\n</body>`) : html + tag;
}
