import type { Blueprint } from '../types';
import { CONTACT, VISIT, home, page } from '../parts';

/** Clinics, salons and gyms — the businesses somebody books rather than buys. */
export const CARE_BLUEPRINTS: Blueprint[] = [
  {
    id: 'nova',
    name: 'Nova',
    industry: 'health',
    businessTypes: ['Dental clinic', 'Orthodontist', 'Implant centre'],
    style: 'clinical',
    note: 'Calm and credentialled. Certifications near the top, results shown rather than claimed.',
    design: 'clinic',
    vertical: 'clinic',
    action: 'Book an appointment',
    features: ['booking', 'enquiries', 'multipage'],
    layouts: { hero: 'split', features: 'checks', split: 'points', team: 'cards', hours: 'location' },
    seoDescription: 'Treatments, the dentists, appointment times and where to find us.',
    pages: [
      home('announcement', 'hero', 'logos', 'services', 'split', 'team', 'beforeafter', 'features', 'steps', 'stats', 'testimonials', 'faq', 'hours', 'cta'),
      page('treatments.html', 'Treatments', 'hero', 'services', 'pricing', 'split', 'steps', 'faq', 'cta'),
      page('doctors.html', 'Our dentists', 'hero', 'team', 'logos', 'stats', 'testimonials', 'cta'),
      page('appointments.html', 'Appointments', 'hero', 'steps', 'split', 'hours', 'faq', 'contact'),
      VISIT,
    ],
  },
  {
    id: 'meridian-health',
    name: 'Meridian Health',
    industry: 'health',
    businessTypes: ['Multi-speciality clinic', 'Diagnostics', 'Polyclinic'],
    style: 'modern',
    note: 'A bigger practice. Departments, doctors and timings, organised so nobody has to ring to ask.',
    design: 'clinic',
    vertical: 'clinic',
    paletteBrief:
      'Cool and clean: near-white ground, deep navy or teal text, one confident accent. Nothing that reads as a warning colour.',
    action: 'Book a consultation',
    features: ['booking', 'enquiries', 'multipage'],
    layouts: { hero: 'centre', services: 'cards', features: 'checks', split: 'columns', hours: 'location' },
    seoDescription: 'Departments, consultants, timings, tests and appointment booking.',
    pages: [
      home('announcement', 'hero', 'logos', 'services', 'features', 'team', 'split', 'stats', 'steps', 'testimonials', 'faq', 'hours', 'cta'),
      page('departments.html', 'Departments', 'hero', 'services', 'split', 'faq', 'cta'),
      page('doctors.html', 'Consultants', 'hero', 'team', 'stats', 'logos', 'cta'),
      page('tests.html', 'Tests & packages', 'hero', 'pricing', 'services', 'steps', 'faq', 'cta'),
      VISIT,
    ],
  },
  {
    id: 'restore',
    name: 'Restore',
    industry: 'health',
    businessTypes: ['Physiotherapy', 'Rehabilitation', 'Chiropractor', 'Sports injury'],
    style: 'warm',
    note: 'Recovery-led. The process explained step by step, with results before promises.',
    design: 'lyceum',
    vertical: 'clinic',
    action: 'Book an assessment',
    features: ['booking', 'enquiries', 'multipage'],
    layouts: { hero: 'split', steps: 'timeline', split: 'points', features: 'checks', testimonials: 'feature' },
    seoDescription: 'Conditions treated, how the programme works, and what recovery looks like.',
    pages: [
      home('hero', 'split', 'services', 'steps', 'beforeafter', 'team', 'stats', 'testimonials', 'features', 'faq', 'hours', 'cta'),
      page('conditions.html', 'What we treat', 'hero', 'services', 'split', 'faq', 'cta'),
      page('programme.html', 'How it works', 'hero', 'steps', 'pricing', 'testimonials', 'faq', 'cta'),
      VISIT,
    ],
  },

  {
    id: 'atelier-hair',
    name: 'Atelier',
    industry: 'beauty',
    businessTypes: ['Hair salon', 'Colour specialist', 'Boutique studio'],
    style: 'editorial',
    note: 'Unhurried and expensive-looking. Photographs given room, the price list set as type.',
    design: 'atelier',
    vertical: 'salon',
    action: 'Book an appointment',
    features: ['booking', 'portfolio', 'enquiries', 'multipage'],
    layouts: { hero: 'editorial', services: 'index', gallery: 'stack', team: 'rail', hours: 'location' },
    seoDescription: 'Services and prices, the stylists, and how to book.',
    pages: [
      home('hero', 'about', 'services', 'gallery', 'team', 'beforeafter', 'split', 'testimonials', 'hours', 'cta'),
      page('services.html', 'Services & prices', 'hero', 'services', 'pricing', 'steps', 'faq', 'cta'),
      page('work.html', 'Our work', 'hero', 'gallery', 'beforeafter', 'testimonials', 'cta'),
      page('team.html', 'Stylists', 'hero', 'team', 'about', 'stats', 'cta'),
      VISIT,
    ],
  },
  {
    id: 'lumen-spa',
    name: 'Lumen Spa',
    industry: 'beauty',
    businessTypes: ['Spa', 'Wellness centre', 'Ayurvedic centre'],
    style: 'minimal',
    note: 'Quiet, warm and slow. Treatments described properly, nothing shouting.',
    design: 'lyceum',
    vertical: 'salon',
    paletteBrief:
      'Warm neutrals — sand, clay, oat — with one muted green or terracotta accent. Low contrast, nothing clinical.',
    action: 'Book a treatment',
    features: ['booking', 'enquiries', 'multipage'],
    layouts: { hero: 'centre', services: 'rows', split: 'media', gallery: 'grid', hours: 'location' },
    seoDescription: 'Treatments, therapists, packages and opening hours.',
    pages: [
      home('hero', 'about', 'services', 'split', 'gallery', 'pricing', 'testimonials', 'faq', 'hours', 'cta'),
      page('treatments.html', 'Treatments', 'hero', 'services', 'pricing', 'steps', 'faq', 'cta'),
      page('packages.html', 'Packages', 'hero', 'pricing', 'split', 'testimonials', 'cta'),
      VISIT,
    ],
  },
  {
    id: 'sharp',
    name: 'Sharp',
    industry: 'beauty',
    businessTypes: ['Barber shop', 'Grooming lounge', 'Men’s salon'],
    style: 'bold',
    note: 'Dark, graphic and quick to read. Price list, walk-in hours, done.',
    design: 'forge',
    vertical: 'salon',
    action: 'Book a chair',
    features: ['booking', 'enquiries'],
    layouts: { hero: 'fullbleed', services: 'numbered', gallery: 'feed', stats: 'band', hours: 'location' },
    seoDescription: 'Cuts, prices, walk-in times and where we are.',
    pages: [
      home('announcement', 'hero', 'services', 'stats', 'split', 'gallery', 'team', 'testimonials', 'hours', 'faq', 'cta'),
      page('prices.html', 'Prices', 'hero', 'services', 'pricing', 'features', 'faq', 'cta'),
      VISIT,
    ],
  },

  {
    id: 'ironworks',
    name: 'Ironworks',
    industry: 'fitness',
    businessTypes: ['Strength gym', 'CrossFit box', 'Powerlifting'],
    style: 'bold',
    note: 'Heavy and confident. Timetable and trial signup above everything else.',
    design: 'forge',
    vertical: 'gym',
    action: 'Start a free trial',
    features: ['booking', 'enquiries', 'multipage'],
    layouts: { hero: 'fullbleed', stats: 'band', services: 'numbered', features: 'checks', gallery: 'mosaic' },
    seoDescription: 'Class timetable, coaches, membership prices and a free trial.',
    pages: [
      home('announcement', 'hero', 'stats', 'services', 'split', 'team', 'gallery', 'pricing', 'testimonials', 'faq', 'hours', 'cta'),
      page('timetable.html', 'Timetable', 'hero', 'services', 'hours', 'steps', 'faq', 'cta'),
      page('membership.html', 'Membership', 'hero', 'pricing', 'features', 'split', 'faq', 'cta'),
      page('coaches.html', 'Coaches', 'hero', 'team', 'stats', 'testimonials', 'cta'),
      VISIT,
    ],
  },
  {
    id: 'stillpoint',
    name: 'Stillpoint',
    industry: 'fitness',
    businessTypes: ['Yoga studio', 'Pilates', 'Meditation'],
    style: 'minimal',
    note: 'Quiet and roomy. The schedule and the first class, nothing else competing.',
    design: 'lyceum',
    vertical: 'gym',
    paletteBrief:
      'Soft and warm: paper or oat ground, ink text, a single muted accent. Generous white space, low contrast.',
    action: 'Book a first class',
    features: ['booking', 'enquiries', 'multipage'],
    layouts: { hero: 'centre', services: 'rows', split: 'points', gallery: 'grid', hours: 'location' },
    seoDescription: 'Class schedule, teachers, passes and your first class.',
    pages: [
      home('hero', 'about', 'services', 'hours', 'team', 'split', 'testimonials', 'pricing', 'faq', 'cta'),
      page('classes.html', 'Classes', 'hero', 'services', 'hours', 'faq', 'cta'),
      page('teachers.html', 'Teachers', 'hero', 'team', 'about', 'testimonials', 'cta'),
      CONTACT,
    ],
  },
  {
    id: 'tempo',
    name: 'Tempo',
    industry: 'fitness',
    businessTypes: ['Personal trainer', 'Dance studio', 'Martial arts'],
    style: 'modern',
    note: 'One coach, one promise. Results, programme, price, book.',
    design: 'circuit',
    vertical: 'gym',
    action: 'Book a session',
    features: ['booking', 'landing', 'enquiries'],
    layouts: { hero: 'split', steps: 'timeline', features: 'checks', testimonials: 'feature', stats: 'inline' },
    seoDescription: 'Programmes, results, prices and how to start.',
    pages: [
      home('announcement', 'hero', 'split', 'stats', 'services', 'steps', 'beforeafter', 'testimonials', 'pricing', 'faq', 'cta'),
      page('programmes.html', 'Programmes', 'hero', 'services', 'pricing', 'steps', 'faq', 'cta'),
      CONTACT,
    ],
  },
];
