import type { Blueprint } from '../types';
import { CONTACT, VISIT, home, page, SHOP_PAGES, SHOP_HOME_SLOTS } from '../parts';

/** Shops, and the people who sell their own work. */
export const COMMERCE_BLUEPRINTS: Blueprint[] = [
  {
    id: 'vitrine',
    name: 'Vitrine',
    industry: 'retail',
    businessTypes: ['Online store', 'Multi-category shop', 'Marketplace'],
    style: 'modern',
    note: 'A real storefront. Departments and stock on the home page, not behind a Shop link.',
    design: 'vitrine',
    vertical: 'retail',
    action: 'Buy something',
    features: ['shop', 'multipage', 'enquiries'],
    layouts: { hero: 'split', features: 'checks', services: 'cards', split: 'points', gallery: 'grid' },
    seoDescription: 'Products, prices, delivery and how to order.',
    pages: [
      {
        ...home('announcement', 'hero', 'features', 'split', 'logos', 'testimonials', 'faq', 'cta'),
        shopBands: SHOP_HOME_SLOTS,
      },
      ...SHOP_PAGES,
      page('about.html', 'Our story', 'hero', 'about', 'steps', 'stats', 'gallery', 'cta'),
      page('delivery.html', 'Delivery & returns', 'hero', 'split', 'steps', 'faq', 'cta'),
      CONTACT,
    ],
  },
  {
    id: 'lacquer',
    name: 'Lacquer',
    industry: 'retail',
    businessTypes: ['Jewellery', 'Boutique', 'Luxury goods'],
    style: 'premium',
    note: 'Fewer things, shown better. Large photography, small type, nothing rushed.',
    design: 'atelier',
    vertical: 'retail',
    paletteBrief:
      'Deep and warm — ink, oxblood or forest — with gold or bone as the accent. Restrained, never bright.',
    action: 'Shop the collection',
    features: ['shop', 'portfolio', 'multipage'],
    layouts: { hero: 'editorial', gallery: 'stack', split: 'media', services: 'index', testimonials: 'feature' },
    seoDescription: 'The collection, the craft behind it, and how to order.',
    pages: [
      {
        ...home('hero', 'about', 'split', 'features', 'gallery', 'steps', 'testimonials', 'logos', 'cta'),
        shopBands: SHOP_HOME_SLOTS,
      },
      ...SHOP_PAGES,
      page('craft.html', 'The craft', 'hero', 'about', 'steps', 'gallery', 'stats', 'cta'),
      page('care.html', 'Care & returns', 'hero', 'faq', 'split', 'cta'),
      CONTACT,
    ],
  },
  {
    id: 'market',
    name: 'Market',
    industry: 'retail',
    businessTypes: ['Grocery', 'Kirana', 'Farm shop', 'Bulk supplier'],
    style: 'warm',
    note: 'Everyday shopping. Wide catalogue, honest prices, delivery slots up front.',
    design: 'harvest',
    vertical: 'retail',
    action: 'Order for delivery',
    features: ['shop', 'multipage', 'enquiries'],
    layouts: { hero: 'split', features: 'checks', services: 'rows', hours: 'location', stats: 'inline' },
    seoDescription: 'What we stock, delivery areas and slots, and how to order.',
    pages: [
      {
        ...home('announcement', 'hero', 'features', 'split', 'steps', 'stats', 'testimonials', 'faq', 'hours', 'cta'),
        shopBands: SHOP_HOME_SLOTS,
      },
      ...SHOP_PAGES,
      page('delivery.html', 'Delivery', 'hero', 'steps', 'features', 'faq', 'contact'),
      VISIT,
    ],
  },

  {
    id: 'silverpoint',
    name: 'Silverpoint',
    industry: 'creative',
    businessTypes: ['Wedding photographer', 'Portrait studio', 'Videographer'],
    style: 'editorial',
    note: 'The work, uninterrupted. Galleries at full width, packages kept out of the way until asked for.',
    design: 'atelier',
    vertical: 'photography',
    action: 'Check your date',
    features: ['portfolio', 'enquiries', 'multipage'],
    layouts: { hero: 'editorial', gallery: 'stack', services: 'index', steps: 'timeline', testimonials: 'feature' },
    seoDescription: 'Galleries, packages, availability and how to book.',
    pages: [
      home('hero', 'gallery', 'about', 'services', 'steps', 'testimonials', 'stats', 'faq', 'cta'),
      page('galleries.html', 'Galleries', 'hero', 'gallery', 'testimonials', 'cta'),
      page('packages.html', 'Packages', 'hero', 'pricing', 'services', 'steps', 'faq', 'cta'),
      page('about.html', 'About', 'hero', 'about', 'split', 'logos', 'cta'),
      CONTACT,
    ],
  },
  {
    id: 'index-folio',
    name: 'Index',
    industry: 'creative',
    businessTypes: ['Designer', 'Illustrator', 'Freelancer', 'Art director'],
    style: 'minimal',
    note: 'A list, not a shop window. Selected work, what you do, how to reach you.',
    design: 'lumen',
    vertical: 'agency',
    action: 'Start a project',
    features: ['portfolio', 'enquiries'],
    layouts: { hero: 'centre', services: 'index', gallery: 'grid', split: 'columns', stats: 'inline' },
    seoDescription: 'Selected work, services, and how to get in touch.',
    pages: [
      home('hero', 'gallery', 'services', 'about', 'split', 'logos', 'testimonials', 'cta'),
      page('work.html', 'Work', 'hero', 'gallery', 'testimonials', 'cta'),
      page('about.html', 'About', 'hero', 'about', 'services', 'stats', 'logos', 'cta'),
      CONTACT,
    ],
  },
  {
    id: 'reel',
    name: 'Reel',
    industry: 'creative',
    businessTypes: ['Production house', 'Content studio', 'Film maker'],
    style: 'bold',
    note: 'Dark and cinematic. Showreel first, clients second, brief form last.',
    design: 'forge',
    vertical: 'photography',
    action: 'Send a brief',
    features: ['portfolio', 'enquiries', 'multipage'],
    layouts: { hero: 'fullbleed', gallery: 'mosaic', services: 'numbered', logos: 'band', stats: 'band' },
    seoDescription: 'Our work, clients, services and how to brief us.',
    pages: [
      home('hero', 'gallery', 'logos', 'services', 'split', 'stats', 'testimonials', 'steps', 'faq', 'cta'),
      page('work.html', 'Work', 'hero', 'gallery', 'logos', 'cta'),
      page('services.html', 'Services', 'hero', 'services', 'steps', 'pricing', 'faq', 'cta'),
      CONTACT,
    ],
  },
];
