import type { Blueprint } from '../types';
import { CONTACT, VISIT, home, page } from '../parts';

/** Food, hotels and travel, and the events business around both. */
export const HOSPITALITY_BLUEPRINTS: Blueprint[] = [
  {
    id: 'lunaire',
    name: 'Lunaire',
    industry: 'food',
    businessTypes: ['Fine dining', 'Bistro', 'Wine bar'],
    style: 'premium',
    note: 'Candlelit and unhurried. Oversized serif, dark room, the menu treated as writing.',
    design: 'kiln',
    vertical: 'restaurant',
    action: 'Book a table',
    features: ['booking', 'menu', 'multipage', 'enquiries'],
    layouts: { hero: 'editorial', menu: 'index', gallery: 'stack', testimonials: 'feature', hours: 'location' },
    seoDescription: 'Menu, reservations, opening hours and directions.',
    pages: [
      home('announcement', 'hero', 'about', 'menu', 'split', 'gallery', 'team', 'testimonials', 'stats', 'hours', 'cta'),
      page('menu.html', 'Menu', 'hero', 'menu', 'pricing', 'split', 'faq', 'cta'),
      page('story.html', 'Our story', 'hero', 'about', 'team', 'stats', 'gallery', 'cta'),
      page('private.html', 'Private dining', 'hero', 'split', 'services', 'pricing', 'faq', 'contact'),
      VISIT,
    ],
  },
  {
    id: 'counter',
    name: 'Counter',
    industry: 'food',
    businessTypes: ['Café', 'Bakery', 'Coffee shop', 'Deli'],
    style: 'warm',
    note: 'Bright and busy. What is out of the oven today, above everything else.',
    design: 'harvest',
    vertical: 'restaurant',
    action: 'Order or drop in',
    features: ['menu', 'enquiries', 'multipage'],
    layouts: { hero: 'split', menu: 'cards', gallery: 'feed', features: 'checks', hours: 'location' },
    seoDescription: 'What we bake, when we open, and where to find us.',
    pages: [
      home('announcement', 'hero', 'menu', 'about', 'features', 'gallery', 'testimonials', 'hours', 'cta'),
      page('menu.html', 'What we make', 'hero', 'menu', 'split', 'faq', 'cta'),
      page('orders.html', 'Pre-orders', 'hero', 'services', 'steps', 'pricing', 'faq', 'contact'),
      VISIT,
    ],
  },
  {
    id: 'tandoor',
    name: 'Tandoor',
    industry: 'food',
    businessTypes: ['Family restaurant', 'Dhaba', 'Cloud kitchen', 'Takeaway'],
    style: 'bold',
    note: 'Loud and hungry. Big photographs, a menu you can read at arm’s length, delivery up front.',
    design: 'forge',
    vertical: 'restaurant',
    action: 'Order now',
    paletteBrief:
      'Deep charcoal or oxblood ground with one hot accent — saffron, chilli red or turmeric. Appetising, never pastel.',
    features: ['menu', 'enquiries', 'multipage'],
    layouts: { hero: 'fullbleed', menu: 'cards', gallery: 'mosaic', stats: 'band', features: 'checks' },
    seoDescription: 'The full menu, delivery, party orders and directions.',
    pages: [
      home('announcement', 'hero', 'features', 'menu', 'gallery', 'split', 'stats', 'testimonials', 'hours', 'cta'),
      page('menu.html', 'Full menu', 'hero', 'menu', 'pricing', 'faq', 'cta'),
      page('parties.html', 'Party orders', 'hero', 'split', 'services', 'pricing', 'steps', 'faq', 'contact'),
      VISIT,
    ],
  },

  {
    id: 'meridian',
    name: 'Meridian',
    industry: 'hospitality',
    businessTypes: ['Hotel', 'Resort', 'Boutique stay'],
    style: 'premium',
    note: 'A quiet, expensive-feeling stay. Rooms shown one at a time, with room to breathe.',
    design: 'estate',
    vertical: 'travel',
    action: 'Check availability',
    features: ['rooms', 'booking', 'multipage', 'enquiries'],
    layouts: { hero: 'showcase', services: 'rows', gallery: 'stack', split: 'media', testimonials: 'feature' },
    seoDescription: 'Rooms, rates, facilities and how to reach us.',
    pages: [
      home('hero', 'about', 'services', 'split', 'gallery', 'features', 'testimonials', 'logos', 'stats', 'cta'),
      page('rooms.html', 'Rooms', 'hero', 'services', 'pricing', 'features', 'faq', 'cta'),
      page('dining.html', 'Dining', 'hero', 'menu', 'gallery', 'hours', 'cta'),
      page('facilities.html', 'Facilities', 'hero', 'features', 'gallery', 'split', 'faq', 'cta'),
      CONTACT,
    ],
  },
  {
    id: 'compass',
    name: 'Compass',
    industry: 'hospitality',
    businessTypes: ['Travel agency', 'Tour operator', 'Trek company'],
    style: 'modern',
    note: 'Packages first. Where you go, what it costs, when it leaves.',
    design: 'estate',
    vertical: 'travel',
    action: 'Enquire about a trip',
    features: ['listings', 'enquiries', 'multipage'],
    layouts: { hero: 'split', services: 'cards', gallery: 'grid', steps: 'timeline', features: 'checks' },
    seoDescription: 'Tours, packages, departure dates and what is included.',
    pages: [
      home('announcement', 'hero', 'services', 'features', 'gallery', 'steps', 'stats', 'testimonials', 'faq', 'cta'),
      page('packages.html', 'Packages', 'hero', 'services', 'pricing', 'split', 'faq', 'cta'),
      page('destinations.html', 'Destinations', 'hero', 'gallery', 'services', 'testimonials', 'cta'),
      page('about.html', 'About us', 'hero', 'about', 'team', 'stats', 'logos', 'cta'),
      CONTACT,
    ],
  },

  {
    id: 'saffron',
    name: 'Saffron',
    industry: 'events',
    businessTypes: ['Wedding planner', 'Event management', 'Decorator'],
    style: 'editorial',
    note: 'Work-led and romantic. Real weddings carry the page; the services list sits under them.',
    design: 'atelier',
    vertical: 'photography',
    action: 'Check your date',
    features: ['portfolio', 'enquiries', 'multipage'],
    layouts: { hero: 'editorial', gallery: 'mosaic', services: 'index', steps: 'timeline', testimonials: 'feature' },
    seoDescription: 'Weddings and events we have planned, what we do, and what it costs.',
    pages: [
      home('hero', 'gallery', 'about', 'services', 'steps', 'split', 'testimonials', 'stats', 'faq', 'cta'),
      page('work.html', 'Real events', 'hero', 'gallery', 'testimonials', 'cta'),
      page('services.html', 'What we do', 'hero', 'services', 'pricing', 'steps', 'faq', 'cta'),
      CONTACT,
    ],
  },
  {
    id: 'mandap',
    name: 'Mandap',
    industry: 'events',
    businessTypes: ['Banquet hall', 'Caterer', 'Venue'],
    style: 'warm',
    note: 'A venue site. Capacity, packages, dates and a floor you can see.',
    design: 'harvest',
    vertical: 'restaurant',
    action: 'Check availability',
    features: ['booking', 'enquiries', 'multipage'],
    layouts: { hero: 'split', features: 'checks', gallery: 'grid', pricing: 'table', hours: 'location' },
    seoDescription: 'Hall capacity, packages, catering and available dates.',
    pages: [
      home('announcement', 'hero', 'features', 'gallery', 'pricing', 'menu', 'split', 'testimonials', 'faq', 'cta'),
      page('packages.html', 'Packages', 'hero', 'pricing', 'services', 'faq', 'cta'),
      page('gallery.html', 'The venue', 'hero', 'gallery', 'features', 'cta'),
      VISIT,
    ],
  },
];
