import type { Blueprint } from '../types';
import { CONTACT, VISIT, home, page } from '../parts';

/** Education, professional services, software, agencies and causes. */
export const KNOWLEDGE_BLUEPRINTS: Blueprint[] = [
  {
    id: 'lyceum',
    name: 'Lyceum',
    industry: 'education',
    businessTypes: ['Coaching centre', 'Test prep', 'Tuition classes'],
    style: 'modern',
    note: 'Results-led. Who got in where, then the batches, then the fee.',
    design: 'lyceum',
    vertical: 'coaching',
    action: 'Book a demo class',
    features: ['courses', 'enquiries', 'multipage'],
    layouts: { hero: 'split', stats: 'band', services: 'rows', features: 'checks', steps: 'timeline' },
    seoDescription: 'Courses, batch timings, faculty, results and fees.',
    pages: [
      home('announcement', 'hero', 'stats', 'services', 'split', 'team', 'steps', 'testimonials', 'features', 'pricing', 'faq', 'hours', 'cta'),
      page('courses.html', 'Courses', 'hero', 'services', 'pricing', 'hours', 'faq', 'cta'),
      page('results.html', 'Results', 'hero', 'stats', 'testimonials', 'gallery', 'cta'),
      page('faculty.html', 'Faculty', 'hero', 'team', 'about', 'logos', 'cta'),
      VISIT,
    ],
  },
  {
    id: 'campus',
    name: 'Campus',
    industry: 'education',
    businessTypes: ['School', 'College', 'Pre-school'],
    style: 'warm',
    note: 'A place, not a course list. Life on campus, admissions, and what the day looks like.',
    design: 'harvest',
    vertical: 'coaching',
    action: 'Enquire about admission',
    features: ['courses', 'enquiries', 'multipage'],
    layouts: { hero: 'showcase', gallery: 'mosaic', features: 'checks', steps: 'timeline', split: 'media' },
    seoDescription: 'Admissions, curriculum, facilities and campus life.',
    pages: [
      home('announcement', 'hero', 'about', 'features', 'gallery', 'split', 'stats', 'team', 'testimonials', 'steps', 'faq', 'cta'),
      page('admissions.html', 'Admissions', 'hero', 'steps', 'pricing', 'faq', 'contact'),
      page('academics.html', 'Academics', 'hero', 'services', 'split', 'team', 'faq', 'cta'),
      page('campus.html', 'Campus life', 'hero', 'gallery', 'features', 'stats', 'cta'),
      VISIT,
    ],
  },
  {
    id: 'terminal',
    name: 'Terminal',
    industry: 'education',
    businessTypes: ['Computer classes', 'Skills training', 'Certification centre'],
    style: 'modern',
    note: 'Job-outcome first. Syllabus, placement, batch dates and fee, in that order.',
    design: 'circuit',
    vertical: 'coaching',
    action: 'Join the next batch',
    features: ['courses', 'enquiries', 'multipage'],
    layouts: { hero: 'split', services: 'numbered', features: 'checks', steps: 'timeline', stats: 'band' },
    seoDescription: 'Courses, syllabus, placement record, batch dates and fees.',
    pages: [
      home('announcement', 'hero', 'stats', 'services', 'split', 'steps', 'logos', 'testimonials', 'pricing', 'faq', 'hours', 'cta'),
      page('courses.html', 'Courses', 'hero', 'services', 'pricing', 'faq', 'cta'),
      page('placement.html', 'Placement', 'hero', 'stats', 'logos', 'testimonials', 'steps', 'cta'),
      VISIT,
    ],
  },

  {
    id: 'chamber',
    name: 'Chamber',
    industry: 'professional',
    businessTypes: ['Law firm', 'Advocate', 'Legal consultant'],
    style: 'premium',
    note: 'Sober and precise. Practice areas, the people, and a consultation that is easy to ask for.',
    design: 'clinic',
    vertical: 'legal',
    paletteBrief:
      'Restrained and serious: ivory or slate ground, deep ink text, one muted accent — burgundy, navy or bronze.',
    action: 'Request a consultation',
    features: ['enquiries', 'multipage'],
    layouts: { hero: 'split', services: 'index', split: 'points', team: 'cards', features: 'checks' },
    seoDescription: 'Practice areas, the lawyers, and how to arrange a consultation.',
    pages: [
      home('hero', 'services', 'split', 'team', 'stats', 'logos', 'steps', 'testimonials', 'faq', 'cta'),
      page('practice.html', 'Practice areas', 'hero', 'services', 'split', 'faq', 'cta'),
      page('people.html', 'People', 'hero', 'team', 'logos', 'stats', 'cta'),
      page('consultation.html', 'Consultation', 'hero', 'steps', 'pricing', 'faq', 'contact'),
      CONTACT,
    ],
  },
  {
    id: 'ledger',
    name: 'Ledger',
    industry: 'professional',
    businessTypes: ['Chartered accountant', 'Tax consultant', 'Audit firm'],
    style: 'minimal',
    note: 'Plain and reassuring. Services, deadlines, fees, and somebody who answers the phone.',
    design: 'clinic',
    vertical: 'finance',
    action: 'Book a consultation',
    features: ['enquiries', 'multipage'],
    layouts: { hero: 'centre', services: 'rows', features: 'checks', split: 'columns', steps: 'numbered' },
    seoDescription: 'Accounting, tax and compliance services, fees and deadlines.',
    pages: [
      home('announcement', 'hero', 'services', 'features', 'split', 'steps', 'stats', 'team', 'testimonials', 'faq', 'cta'),
      page('services.html', 'Services', 'hero', 'services', 'pricing', 'split', 'faq', 'cta'),
      page('deadlines.html', 'Key dates', 'hero', 'hours', 'split', 'faq', 'cta'),
      CONTACT,
    ],
  },
  {
    id: 'compass-advice',
    name: 'Compass Advisory',
    industry: 'professional',
    businessTypes: ['Financial advisor', 'Insurance advisor', 'Wealth manager'],
    style: 'modern',
    note: 'Trust before product. How the advice works, what it costs, who gives it.',
    design: 'estate',
    vertical: 'finance',
    action: 'Book a review',
    features: ['enquiries', 'multipage'],
    layouts: { hero: 'split', split: 'points', steps: 'timeline', features: 'checks', stats: 'inline' },
    seoDescription: 'Financial planning and insurance advice, how it works and what it costs.',
    pages: [
      home('hero', 'split', 'services', 'steps', 'stats', 'logos', 'team', 'testimonials', 'features', 'faq', 'cta'),
      page('services.html', 'What we do', 'hero', 'services', 'pricing', 'split', 'faq', 'cta'),
      page('process.html', 'How it works', 'hero', 'steps', 'features', 'faq', 'contact'),
      CONTACT,
    ],
  },

  {
    id: 'circuit',
    name: 'Circuit',
    industry: 'software',
    businessTypes: ['SaaS product', 'B2B software', 'Developer tool'],
    style: 'modern',
    note: 'The classic product page, done properly. Problem, product, proof, price.',
    design: 'circuit',
    vertical: 'agency',
    action: 'Start free',
    features: ['landing', 'multipage', 'enquiries'],
    layouts: { hero: 'centre', split: 'columns', features: 'bento', steps: 'numbered', logos: 'band' },
    seoDescription: 'What the product does, who it is for, how it works and what it costs.',
    pages: [
      home('announcement', 'hero', 'logos', 'split', 'features', 'steps', 'services', 'stats', 'testimonials', 'pricing', 'faq', 'cta'),
      page('features.html', 'Features', 'hero', 'features', 'split', 'services', 'faq', 'cta'),
      page('pricing.html', 'Pricing', 'hero', 'pricing', 'features', 'faq', 'cta'),
      page('about.html', 'About', 'hero', 'about', 'team', 'logos', 'stats', 'cta'),
      CONTACT,
    ],
  },
  {
    id: 'signal',
    name: 'Signal',
    industry: 'software',
    businessTypes: ['AI product', 'Startup', 'Mobile app'],
    style: 'bold',
    note: 'Dark, confident and short. One promise, one demo, one button.',
    design: 'forge',
    vertical: 'agency',
    paletteBrief:
      'Near-black ground with a single luminous accent — electric lime, cyan or violet. High contrast, no gradients beyond one.',
    action: 'Request a demo',
    features: ['landing', 'enquiries'],
    layouts: { hero: 'fullbleed', features: 'bento', split: 'columns', stats: 'band', logos: 'band' },
    seoDescription: 'What it does, who it is for, and how to see it working.',
    pages: [
      home('announcement', 'hero', 'logos', 'split', 'features', 'gallery', 'steps', 'stats', 'testimonials', 'pricing', 'faq', 'cta'),
      page('product.html', 'Product', 'hero', 'features', 'split', 'gallery', 'faq', 'cta'),
      CONTACT,
    ],
  },
  {
    id: 'stack',
    name: 'Stack',
    industry: 'software',
    businessTypes: ['IT services', 'Software agency', 'Systems integrator'],
    style: 'minimal',
    note: 'Capability and proof. What you build, who you built it for, how engagements run.',
    design: 'lumen',
    vertical: 'agency',
    action: 'Book a call',
    features: ['enquiries', 'multipage'],
    layouts: { hero: 'split', services: 'numbered', logos: 'row', steps: 'timeline', split: 'points' },
    seoDescription: 'Services, case studies, how we work and how to start.',
    pages: [
      home('hero', 'logos', 'services', 'split', 'gallery', 'steps', 'stats', 'team', 'testimonials', 'faq', 'cta'),
      page('services.html', 'Services', 'hero', 'services', 'split', 'pricing', 'faq', 'cta'),
      page('work.html', 'Case studies', 'hero', 'gallery', 'logos', 'testimonials', 'stats', 'cta'),
      CONTACT,
    ],
  },

  {
    id: 'broadcast',
    name: 'Broadcast',
    industry: 'agency',
    businessTypes: ['Digital marketing', 'SEO agency', 'Social media'],
    style: 'bold',
    note: 'Numbers forward. Results, clients, services, call. Nothing decorative.',
    design: 'circuit',
    vertical: 'agency',
    action: 'Get a proposal',
    features: ['enquiries', 'multipage'],
    layouts: { hero: 'split', stats: 'band', services: 'numbered', logos: 'row', split: 'points' },
    seoDescription: 'Results we have delivered, services, clients and how to brief us.',
    pages: [
      home('announcement', 'hero', 'stats', 'logos', 'services', 'split', 'steps', 'gallery', 'testimonials', 'pricing', 'faq', 'cta'),
      page('services.html', 'Services', 'hero', 'services', 'pricing', 'steps', 'faq', 'cta'),
      page('results.html', 'Results', 'hero', 'stats', 'gallery', 'testimonials', 'logos', 'cta'),
      CONTACT,
    ],
  },
  {
    id: 'kiln-studio',
    name: 'Kiln',
    industry: 'agency',
    businessTypes: ['Branding studio', 'Design agency', 'Creative consultancy'],
    style: 'editorial',
    note: 'Craft-led. Case studies at length, the process told once, no stock imagery.',
    design: 'kiln',
    vertical: 'agency',
    action: 'Start a project',
    features: ['portfolio', 'enquiries', 'multipage'],
    layouts: { hero: 'editorial', gallery: 'stack', services: 'index', steps: 'timeline', split: 'media' },
    seoDescription: 'Case studies, services, the studio and how projects run.',
    pages: [
      home('hero', 'gallery', 'about', 'services', 'split', 'steps', 'logos', 'testimonials', 'stats', 'faq', 'cta'),
      page('work.html', 'Work', 'hero', 'gallery', 'logos', 'testimonials', 'cta'),
      page('studio.html', 'Studio', 'hero', 'about', 'team', 'stats', 'cta'),
      CONTACT,
    ],
  },

  {
    id: 'commons',
    name: 'Commons',
    industry: 'community',
    businessTypes: ['NGO', 'Trust', 'Foundation', 'Charity'],
    style: 'warm',
    note: 'The work and the need, in that order. Impact shown, donation never more than one click away.',
    design: 'harvest',
    vertical: 'coaching',
    action: 'Donate',
    features: ['enquiries', 'multipage'],
    layouts: { hero: 'showcase', stats: 'band', gallery: 'mosaic', split: 'points', steps: 'timeline' },
    seoDescription: 'What we do, who it reaches, how it is funded and how to help.',
    pages: [
      home('announcement', 'hero', 'split', 'stats', 'services', 'gallery', 'steps', 'testimonials', 'logos', 'team', 'faq', 'cta'),
      page('work.html', 'Our work', 'hero', 'services', 'gallery', 'stats', 'cta'),
      page('donate.html', 'Donate', 'hero', 'split', 'steps', 'faq', 'contact'),
      page('about.html', 'About us', 'hero', 'about', 'team', 'logos', 'stats', 'cta'),
      CONTACT,
    ],
  },
  {
    id: 'byline',
    name: 'Byline',
    industry: 'community',
    businessTypes: ['Personal brand', 'Speaker', 'Author', 'Consultant'],
    style: 'minimal',
    note: 'One person, plainly. What you do, what you have written, how to book you.',
    design: 'lumen',
    vertical: 'agency',
    action: 'Get in touch',
    features: ['portfolio', 'landing', 'enquiries'],
    layouts: { hero: 'split', services: 'index', logos: 'row', split: 'columns', testimonials: 'feature' },
    seoDescription: 'About, what I do, talks and writing, and how to reach me.',
    pages: [
      home('hero', 'about', 'services', 'logos', 'split', 'gallery', 'steps', 'testimonials', 'stats', 'faq', 'cta'),
      page('work.html', 'Work', 'hero', 'gallery', 'services', 'testimonials', 'cta'),
      CONTACT,
    ],
  },
];
