import type { Blueprint } from '../types';
import { CONTACT, VISIT, home, page } from '../parts';

/** Property, the trades that build and fix things, and vehicles. */
export const PROPERTY_BLUEPRINTS: Blueprint[] = [
  {
    id: 'terrace',
    name: 'Terrace',
    industry: 'property',
    businessTypes: ['Estate agency', 'Lettings', 'Property consultant'],
    style: 'modern',
    note: 'Listings-led. A property list you can scan in a second, agents underneath.',
    design: 'estate',
    vertical: 'real-estate',
    action: 'Book a viewing',
    features: ['listings', 'enquiries', 'multipage'],
    layouts: { hero: 'split', services: 'rows', features: 'checks', split: 'points', team: 'cards' },
    seoDescription: 'Properties for sale and rent, the areas we cover, and a free valuation.',
    pages: [
      home('hero', 'services', 'features', 'split', 'team', 'stats', 'logos', 'testimonials', 'steps', 'faq', 'cta'),
      page('properties.html', 'Properties', 'hero', 'services', 'gallery', 'faq', 'cta'),
      page('valuation.html', 'Free valuation', 'hero', 'steps', 'split', 'stats', 'faq', 'contact'),
      page('agents.html', 'Our agents', 'hero', 'team', 'stats', 'testimonials', 'cta'),
      CONTACT,
    ],
  },
  {
    id: 'foundation',
    name: 'Foundation',
    industry: 'property',
    businessTypes: ['Builder', 'Contractor', 'Property developer'],
    style: 'bold',
    note: 'Built and finished. Projects first, capability second, licences in plain sight.',
    design: 'forge',
    vertical: 'interiors',
    action: 'Request a quote',
    features: ['portfolio', 'enquiries', 'multipage'],
    layouts: { hero: 'showcase', gallery: 'mosaic', steps: 'timeline', split: 'points', stats: 'band' },
    seoDescription: 'Projects completed, what we build, licences and how to get a quote.',
    pages: [
      home('hero', 'stats', 'gallery', 'services', 'split', 'steps', 'logos', 'beforeafter', 'testimonials', 'faq', 'cta'),
      page('projects.html', 'Projects', 'hero', 'gallery', 'beforeafter', 'stats', 'cta'),
      page('services.html', 'What we build', 'hero', 'services', 'split', 'steps', 'faq', 'cta'),
      page('quote.html', 'Get a quote', 'hero', 'steps', 'features', 'faq', 'contact'),
      CONTACT,
    ],
  },
  {
    id: 'lathe',
    name: 'Lathe',
    industry: 'property',
    businessTypes: ['Interior designer', 'Architect', 'Design studio'],
    style: 'editorial',
    note: 'Work-led and quiet. Each project shown at full width, the process told once.',
    design: 'atelier',
    vertical: 'interiors',
    action: 'Start a project',
    features: ['portfolio', 'enquiries', 'multipage'],
    layouts: { hero: 'editorial', gallery: 'stack', steps: 'timeline', split: 'media', services: 'index' },
    seoDescription: 'Projects, how we work, what it costs and how to start.',
    pages: [
      home('hero', 'gallery', 'about', 'services', 'steps', 'split', 'beforeafter', 'testimonials', 'logos', 'faq', 'cta'),
      page('work.html', 'Work', 'hero', 'gallery', 'beforeafter', 'testimonials', 'cta'),
      page('process.html', 'How we work', 'hero', 'steps', 'split', 'pricing', 'faq', 'cta'),
      page('studio.html', 'Studio', 'hero', 'about', 'team', 'logos', 'stats', 'cta'),
      CONTACT,
    ],
  },

  {
    id: 'apex-motors',
    name: 'Apex Motors',
    industry: 'automotive',
    businessTypes: ['Car dealership', 'Bike showroom', 'Pre-owned cars'],
    style: 'modern',
    note: 'Stock first. What is on the floor, what it costs, and finance beside it.',
    design: 'circuit',
    vertical: 'automotive',
    action: 'Book a test drive',
    features: ['listings', 'enquiries', 'multipage'],
    layouts: { hero: 'showcase', services: 'cards', features: 'checks', split: 'points', stats: 'band' },
    seoDescription: 'Cars in stock, prices, finance options and test drives.',
    pages: [
      home('announcement', 'hero', 'services', 'logos', 'features', 'split', 'stats', 'steps', 'testimonials', 'faq', 'cta'),
      page('stock.html', 'In stock', 'hero', 'services', 'gallery', 'faq', 'cta'),
      page('finance.html', 'Finance', 'hero', 'split', 'steps', 'pricing', 'faq', 'contact'),
      VISIT,
    ],
  },
  {
    id: 'garage',
    name: 'Garage',
    industry: 'automotive',
    businessTypes: ['Service centre', 'Garage', 'Car wash', 'Tyre shop'],
    style: 'bold',
    note: 'Prices on the wall. What it costs, how long it takes, when you are open.',
    design: 'forge',
    vertical: 'automotive',
    action: 'Book a service',
    features: ['booking', 'enquiries'],
    layouts: { hero: 'split', services: 'rows', features: 'checks', stats: 'inline', hours: 'location' },
    seoDescription: 'Servicing, repairs, prices and booking.',
    pages: [
      home('announcement', 'hero', 'services', 'features', 'pricing', 'steps', 'stats', 'testimonials', 'faq', 'hours', 'cta'),
      page('services.html', 'Services & prices', 'hero', 'services', 'pricing', 'faq', 'cta'),
      VISIT,
    ],
  },

  {
    id: 'callout',
    name: 'Callout',
    industry: 'trades',
    businessTypes: ['Plumber', 'Electrician', 'Emergency repairs'],
    style: 'bold',
    note: 'Built for somebody standing in water at 11pm. Number enormous, areas named, quote form short.',
    design: 'circuit',
    vertical: 'agency',
    action: 'Call now',
    paletteBrief:
      'High contrast and legible on a phone in daylight: near-black or deep blue ground, one bright signal accent.',
    features: ['enquiries', 'landing'],
    layouts: { hero: 'centre', services: 'numbered', features: 'checks', split: 'points', hours: 'inline' },
    seoDescription: 'Emergency callouts, the areas we cover, prices and a free quote.',
    pages: [
      home('announcement', 'hero', 'services', 'features', 'split', 'stats', 'steps', 'testimonials', 'faq', 'hours', 'cta'),
      page('areas.html', 'Areas we cover', 'hero', 'features', 'services', 'faq', 'contact'),
      CONTACT,
    ],
  },
  {
    id: 'haul',
    name: 'Haul',
    industry: 'trades',
    businessTypes: ['Movers & packers', 'Logistics', 'Courier'],
    style: 'modern',
    note: 'Quote-led. What you are moving, where to, and a number the same day.',
    design: 'circuit',
    vertical: 'agency',
    action: 'Get a quote',
    features: ['enquiries', 'multipage'],
    layouts: { hero: 'split', steps: 'timeline', services: 'cards', features: 'checks', stats: 'band' },
    seoDescription: 'Moving and logistics services, coverage, and a same-day quote.',
    pages: [
      home('hero', 'services', 'steps', 'features', 'split', 'stats', 'logos', 'testimonials', 'faq', 'cta'),
      page('services.html', 'What we move', 'hero', 'services', 'pricing', 'faq', 'cta'),
      page('quote.html', 'Get a quote', 'hero', 'steps', 'features', 'faq', 'contact'),
      CONTACT,
    ],
  },
];
