import type { Metadata } from 'next';
import Link from 'next/link';
import { TopNav } from '@/components/marketing/TopNav';
import { Footer } from '@/components/marketing/Footer';
import { CodeWindow } from '@/components/ui/CodeWindow';
import { EmptyState } from '@/components/ui/Card';
import { ButtonLink } from '@/components/ui/Button';
import { createClient } from '@/lib/supabase/server';
import { isSupabaseConfigured } from '@/lib/env';

export const metadata: Metadata = {
  title: 'Showcase',
  description: 'Real sites generated by Lumen, previewed live.',
};

export const revalidate = 300;

export default async function ShowcasePage() {
  let projects: { id: string; name: string; description: string | null; business_type: string | null }[] = [];

  if (isSupabaseConfigured) {
    const supabase = await createClient();
    const { data } = await supabase
      .from('projects')
      .select('id, name, description, business_type')
      .eq('is_template', true)
      .eq('status', 'ready')
      .order('created_at', { ascending: false })
      .limit(9);
    projects = data ?? [];
  }

  return (
    <>
      <div className="relative">
        <div className="lumen-glow-field" aria-hidden />
        <TopNav />
        <section className="relative mx-auto max-w-shell px-6 pb-14 pt-16 text-center">
          <h1 className="font-display text-[40px] leading-tight text-ink-primary sm:text-[56px]">
            Built with <em className="italic text-accent">one sentence.</em>
          </h1>
          <p className="mx-auto mt-4 max-w-xl text-[15px] text-ink-secondary">
            Every site below is a live preview of real generated output — not a screenshot.
          </p>
        </section>
      </div>

      <section className="mx-auto max-w-shell px-6 pb-24">
        {projects.length === 0 ? (
          <EmptyState
            title="The showcase is filling up"
            description="Published sites appear here as soon as they are approved. Build yours and it could be next."
            action={<ButtonLink href="/signup">Start building →</ButtonLink>}
          />
        ) : (
          <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
            {projects.map((project) => (
              <Link key={project.id} href={`/preview/${project.id}/index.html`} target="_blank">
                <CodeWindow title={`LUMEN / ${project.name.toUpperCase()}`} className="transition hover:border-accent/30">
                  <iframe
                    src={`/preview/${project.id}/index.html`}
                    title={project.name}
                    loading="lazy"
                    sandbox="allow-scripts"
                    className="h-[300px] w-full border-0 bg-white"
                  />
                  <div className="border-t border-hairline px-4 py-3">
                    <p className="text-sm text-ink-primary">{project.name}</p>
                    <p className="mt-0.5 text-[12px] text-ink-muted">
                      {project.description ?? project.business_type ?? 'Generated with Lumen'}
                    </p>
                  </div>
                </CodeWindow>
              </Link>
            ))}
          </div>
        )}
      </section>

      <Footer />
    </>
  );
}
